# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 日拱一兵
subtitle: Quick notes
description: Java后端技术博客，用有趣的方式解读技术
keywords: 后端博客,Java,SpringBoot,ElasticSearch
author: tanθ
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dayarch.top
root: /
# permalink: :year/:month/:day/:title/
permalink: /p/:id.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo:
       github: git@github.com:FraserYu/FraserYu.github.io.git
       coding: git@e.coding.net:dayarch/rgyb.git
  - type: baidu_url_submitter



## 「hexo-theme-material-x」 所属配置 start ********************************************************************
# 网站图标
favicon: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicon.ico

# 作者头像，会出现在文章标题下方，不同于侧边栏的大头像
avatar: https://cdn.jsdelivr.net/gh/FraserYu/img-host/blog-imgavatar.png

# 全局导入
# import:
#   meta:
#   - "<meta name='theme-color' content='#FFFFFF'>"
#   - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
#   - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/browserconfig.xml'>"
#   link:
#   - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicon.ico'>"
#   - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/favicon-32x32.png'>"
#   - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/apple-touch-icon.png'>"
#   - "<link rel='mask-icon' color='#1BC3FB' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/safari-pinned-tab.svg'>"
#   - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/site.webmanifest'>"
  # script:
  #   - "<script type="text/javascript" color="220,220,220" opacity='0.7' zIndex="-2" count="200" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>"

gitalk: 
  clientID: 57bd3ce366ba25a73a1a
  clientSecret: bab4a248180b9ac85b16fb44bf4ba171648f9cab
  repo: myBlogTalk
  owner: FraserYu
  admin: FraserYu

## 「hexo-theme-material-x」 所属配置 end   ********************************************************************

# 百度统计
baidu_analytics_key: f553477a3dc5ab3837e9a4dead4e0bc7

# 谷歌统计
google_analytics_key: UA-147539283-1


# hexo 文章自动截取，如果不设置默认值为 300
excerpt_length: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 百度主动提交
baidu_url_submit:
  count: 5 ## 提交最新的五个链接
  host: dayarch.top ## 百度站长平台中注册的域名
  token: RTJEKTDwof4NixfF ## 准入秘钥
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# 豆瓣插件
douban:
  user: 115784569
  builtin: false
  book:
    title: 读书只为取悦自己
    quote: 阅读让我有说走就走的旅行
  timeout: 10000   

# 源文件备份
backup:
  type: git
  theme: hexo-theme-material-x
  message: Back up my dayarch.top blog
  repository:
    github: git@github.com:FraserYu/FraserYu.github.io.git,backup
    coding: git@e.coding.net:dayarch/rgyb.git,backup