############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      # style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.10.22/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.9/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.9/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0.6/js/volantis.min.js



############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: https://cdn.jsdelivr.net/gh/FraserYu/img-host/blog-imgCube-1s-200px.svg

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: cover  # cover: 封面背景   full: 整个网页背景
  duration: 6000 # 持续时间（毫秒）
  fade: 2500     # 渐变（毫秒）
  images:
    # - https://img.vim-cn.com/29/91197b04c13f512f734a76d4ac422d89dbe229.jpg
    # - https://cdn.jsdelivr.net/gh/FraserYu/img-host/blog-img72732.png
    # - https://cdn.jsdelivr.net/gh/FraserYu/img-host/blog-img756062.png



############################### 自定义 ###############################
# page的封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: Demo
  logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  # search_placeholder: '搜索'
  # 主页封面菜单
  features:
    - name: 主页
      icon: fas fa-home
      url: /
      # rel: nofollow
    - name: 分类
      icon: fas fa-folder-open
      url: /categories/
      # rel: nofollow
    - name: 标签
      icon: fas fa-tags
      url: /tags/
      # rel: nofollow
    - name: 归档
      icon: fas fa-archive
      url: /archives/
      # rel: nofollow
    # - name: 项目
    #   icon: fas fa-code-branch
    #   url: projects/
    # - name: 友链
    #   icon: fas fa-link
    #   url: friends/
    #   rel: nofollow
    # - name: 关于
    #   icon: fas fa-info-circle
    #   url: about/
    #   rel: nofollow
    # - name: 留言板
    #   icon: fas fa-comments
    #   url: comments/
    #   rel: nofollow      


# 桌面端导航栏菜单
menu_desktop:
    - name: 主页
      icon: fas fa-home
      url: /
      # rel: nofollow
    - name: 分类
      icon: fas fa-folder-open
      url: /categories/
      # rel: nofollow
    - name: 标签
      icon: fas fa-tags
      url: /tags/
      # rel: nofollow
    - name: 归档
      icon: fas fa-archive
      url: /archives/
      # rel: nofollow
    # - name: 项目
    #   icon: fas fa-code-branch
    #   url: projects/
    - name: 友链
      icon: fas fa-link
      url: friends/
      rel: nofollow
    # - name: 关于
    #   icon: fas fa-info-circle
    #   url: about/
    #   rel: nofollow
    - name: 留言板
      icon: fas fa-comments
      url: comments/
      rel: nofollow
# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 近期文章
    icon: fas fa-clock
    url: /
  - name: 分类
    icon: fas fa-folder-open
    url: /categories/
    rel: nofollow
  - name: 标签
    icon: fas fa-tags
    url: /tags/
    rel: nofollow
  - name: 归档
    icon: fas fa-archive
    url: /archives/
    rel: nofollow
  # - name: 项目
  #   icon: fas fa-code-branch
  #   url: projects/
  - name: 友链
    icon: fas fa-link
    url: friends/
    rel: nofollow
  # - name: 关于
  #   icon: fas fa-info-circle
  #   url: about/
  #   rel: nofollow
  - name: 留言板
    icon: fas fa-comments
    url: comments/
    rel: nofollow

layout:
  # 文章列表（主页、自定义的列表）布局
  posts:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, categories, top]
    # 列表类页面的侧边栏
    sidebar: [author, plain, list, grid, category, tagcloud, advertise, music]
  # 文章页面布局
  article:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    header: [title, author, date, categories, counter, top]
    footer: [updated, tags, share]
    # 文章页面的侧边栏
    sidebar: [author, toc, grid, category, tagcloud, advertise, list, related_posts]
  # 其他的页面布局暂时等于文章列表


# 侧边栏小部件配置
sidebar:
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/FraserYu/img-host/blog-imgqrcode.jpg
    jinrishici: 从来没有真正的绝境，只有心灵的迷途
  - widget: toc
  - widget: plain
    icon: fas fa-bullhorn
    title: 公告
    body: '博客升级改造中... 如有问题请[留言](/comments/)交流' 
  - widget: advertise
    icon: fas fa-gift
    title: 广告
    body: '<center>这是一个神奇的广告</center>'
  - widget: grid
    icon: fas fa-map-signs
    title: 站内导航
    rows:
      - name: 近期文章
        icon: fas fa-clock
        url: /
      - name: 文章归档
        icon: fas fa-archive
        url: /archives/
        # rel: nofollow
      - name: 并发系列
        icon: fas fa-th-list
        url: /categories/Coding/Java-Concurrency
        # rel: nofollow
      - name: 留言看板
        icon: fas fa-comments
        url: /comments/
        rel: nofollow     
      - name: 维护日志
        icon: fas fa-file
        url: /website/
        rel: nofollow   
      - name: 我的书房
        icon: fas fa-book
        url: /books/
        rel: nofollow                    
      # - name: 开源项目
      #   icon: fas fa-code-branch
      #   url: projects/
      # - name: 我的友链
      #   icon: fas fa-link
      #   url: /friends/
      #   rel: nofollow
      # - name: 主题文档
      #   icon: fas fa-book
      #   url: https://xaoxuu.com/wiki/material-x/
      #   rel: nofollow
      # - name: 关于小站
      #   icon: fas fa-info-circle
      #   url: /about/
      #   rel: nofollow
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: blog/categories/
      animate: rotate90
      target: blank
      # rel: nofollow
  - widget: tagcloud
    icon: fas fa-tags
    more:
      icon: fas fa-expand-arrows-alt
      url: blog/tags/
      animate: rotate90
      target: blank
      # rel: nofollow
  # - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/my/m/music/playlist?id=2565998811
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2565998811     # 歌曲/专辑/歌单 ID
  # - widget: list
  #   icon: fas fa-thumbs-up
  #   title: 强烈推荐
  #   rows:
  #     - name: Hexo脚本（Mac）
  #       url: https://xaoxuu.com/wiki/hexo.sh/
  #     - name: 图床脚本（Mac）
  #       url: https://xaoxuu.com/wiki/vim-cn.sh/
  #     - name: 图片在线压缩
  #       url: https://yasuotu.com
  #     - name: 生成Favicon
  #       url: https://realfavicongenerator.net
  #     - name: 简历主题
  #       url: https://mxclub.github.io/resume/




# 社交信息
# social:
#   - icon: fas fa-rss
#     url: atom.xml
#   - icon: fas fa-envelope
#     url: mailto:me@xaoxuu.com
#   - icon: fab fa-github
#     url: https://github.com/xaoxuu
#   - icon: fas fa-headphones-alt
#     url: https://music.163.com/#/user/home?id=63035382


# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: 微信
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



# footer: '页脚文字，支持[markdown](/)'


############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 
#   clientID: 57bd3ce366ba25a73a1a
#   clientSecret: bab4a248180b9ac85b16fb44bf4ba171648f9cab
#   repo: myBlogTalk
#   owner: FraserYu
#   admin: [FraserYu]
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey


############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true

# OW readmore
readmore:
  enable: true

# 首页动态文本
subtitle: 
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 100 # 打字速度
  backSpeed: 50 # 删除速度
  sub1: 从来没有真正的绝境, 只有心灵的迷途
  sub2: Never really desperate, only the lost of the soul

# google 广告 
googleads:
  auto: true # post.ejs中引入的自动广告
  square: true # advertise.ejs引入的方形卡片广告，在sidebar处可配置

# 页面即时聊天工具
daovoice: true
daovoice_app_id: 8a3d6849

# 站点运行开始时间.
time: 
  enable: true
  year: 2019
  month: 05
  date: 22
  hour: 09
  minute: 09
  second: 06

wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true  

reprint:
  enable: true  